blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: mailto:security@burdenoff.com
    about: Please report security issues via email to our security team
  - name: Support
    url: mailto:support@burdenoff.com
    about: Need help? Contact our support team